name: TnTLevelLimit
main: kero.tntlevel.TnTLevelLimit
version: 1.0
commands:
    tntlevel:
        usage: /tntlevel
        aliases: [tntlevellimit,tntl]
        description: SafetyTnT Commands.