name: TnTLevelLimit
main: kero.tntlevel.TnTLevelLimit
version: ${project.version}
description: TnT Level Limit
author: Kerotein
commands:
    tntlevel:
        usage: /tntlevel
        aliases: [tntlevellimit,tntlevelimit,tntl]
        description: SafetyTnT Commands.